import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

// Register PWA service worker (auto-generated by vite-plugin-pwa)
import { registerSW } from "virtual:pwa-register";

const updateSW = registerSW({
  onNeedRefresh() {
    // Auto-update when a new version is available
    updateSW(true);
  },
  onOfflineReady() {
    console.log("[B.L.U.E.-J.] Offline ready — all assets cached.");
  },
});

createRoot(document.getElementById("root")!).render(<App />);
