import { createRoot } from "react-dom/client";
import App from "./App";
import "./index.css";
import { installErrorInterceptor } from "@/lib/self-correct";
import { useAIProviderStore } from "@/lib/ai-provider";

// Register PWA service worker (auto-generated by vite-plugin-pwa)
import { registerSW } from "virtual:pwa-register";

const updateSW = registerSW({
  onNeedRefresh() {
    // Auto-update when a new version is available
    updateSW(true);
  },
  onOfflineReady() {
    console.log("[B.L.U.E.-J.] Offline ready — all assets cached.");
  },
});

// Install self-correction error interceptor
installErrorInterceptor();

// Detect whether Express server is available (standalone vs hosted)
fetch('/api/health', { method: 'GET' })
  .then((r) => {
    useAIProviderStore.getState().setHasServerAccess(r.ok);
    if (r.ok) useAIProviderStore.getState().loadFromServer();
  })
  .catch(() => {
    useAIProviderStore.getState().setHasServerAccess(false);
    console.log('[B.L.U.E.-J.] Standalone mode — using direct API calls');
  });

createRoot(document.getElementById("root")!).render(<App />);
